export const Product:{id:number; title:string; url:string; price:number; kategori:string;indirim:string}[]= [
    {
        id:1,
        title:"Akıllı Saat",
        url:'/product-img-3.png',
        price:10000,
        kategori:'elektronik',
        indirim:'indirim',

    },
{
    id:2,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:3,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:4,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:5,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:6,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:7,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:8,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
{
    id:9,
    title:"Akıllı Saat",
    url:'/product-img-3.png',
    price:10000,
    kategori:'elektronik',
    indirim:'indirim',
},
]